name: varcall
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - bcftools
  - bedtools
  - bioawk
  - bowtie2
  - bwa
  - bzip2
  - ca-certificates
  - capnproto
  - certifi
  - curl
  - gatk
  - gatk4
  - gsl
  - java-jdk
  - joblib
  - krb5
  - libblas
  - libcblas
  - libgcc-ng
  - libgfortran-ng
  - libopenblas
  - libssh2
  - libstdcxx-ng
  - mash
  - mummer
  - ncurses
  - openjdk
  - openssl
  - perl
  - picard
  - pilon
  - pip
  - python
  - qualimap
  - raxml
  - readline
  - samtools
  - setuptools
  - snpeff
  - sqlite
  - subprocess32
  - tabix
  - tk
  - trimmomatic
  - vcftools
  - wheel
  - xz
  - zlib
